app = "e-scooter-sharing-software"
primary_region = "waw" # lub inny region, który wybrałeś

[build]
  # Fly sam znajdzie Dockerfile w tym folderze

[http_service]
  internal_port = 3000 # Zmień na 8080 lub 5000 jeśli Twoja aplikacja na takim działa
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256